from pathlib import Path

p = Path('api/src/approve-scan.js')
s = p.read_text()

old_func = '''async function writeToGoogleSheet(rows, context) {\n  const token = await getSheetsToken();\n  const range = encodeURIComponent(`${SHEETS_TAB}!A:N`);\n  const res = await fetch(\n    `https://sheets.googleapis.com/v4/spreadsheets/${SHEETS_ID}/values/${range}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,\n    {\n      method: 'POST',\n      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },\n      body: JSON.stringify({ values: rows }),\n    }\n  );\n  if (!res.ok) {\n    const err = await res.text().catch(()=>'');\n    throw new Error(`Google Sheets write failed (${res.status}): ${err.slice(0,300)}`);\n  }\n  const data = await res.json().catch(()=>({}));\n  context.log('[Sheets] Wrote', rows.length, 'row(s) to Google Sheet', data?.updates?.updatedRange || '');\n  return { success:true, updatedRange:data?.updates?.updatedRange || '', rows:rows.length };\n}\n'''

new_func = '''async function writeToGoogleSheet(rows, context) {\n  const expectedBaseIds = [...new Set(rows.map(r => String(r?.[7] || '').match(/(\\d{6}-\\d{3})/)?.[1]).filter(Boolean))];\n  let lastError = null;\n\n  for (let attempt = 1; attempt <= 3; attempt++) {\n    const attemptStart = Date.now();\n    try {\n      const authStart = Date.now();\n      const token = await getSheetsToken();\n      context.log(`[Sheets][timing] attempt ${attempt} auth: ${Date.now()-authStart}ms`);\n\n      const appendStart = Date.now();\n      const range = encodeURIComponent(`${SHEETS_TAB}!A:N`);\n      const res = await fetch(\n        `https://sheets.googleapis.com/v4/spreadsheets/${SHEETS_ID}/values/${range}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,\n        {\n          method: 'POST',\n          headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },\n          body: JSON.stringify({ values: rows }),\n        }\n      );\n      context.log(`[Sheets][timing] attempt ${attempt} append: ${Date.now()-appendStart}ms status=${res.status}`);\n      if (!res.ok) {\n        const err = await res.text().catch(()=>'');\n        throw new Error(`Google Sheets write failed (${res.status}): ${err.slice(0,300)}`);\n      }\n      const data = await res.json().catch(()=>({}));\n\n      const verifyStart = Date.now();\n      const verifyRange = encodeURIComponent(`${SHEETS_TAB}!H1:H`);\n      const verifyRes = await fetch(\n        `https://sheets.googleapis.com/v4/spreadsheets/${SHEETS_ID}/values/${verifyRange}`,\n        { headers: { Authorization: `Bearer ${token}` } }\n      );\n      context.log(`[Sheets][timing] attempt ${attempt} verify-read: ${Date.now()-verifyStart}ms status=${verifyRes.status}`);\n      if (!verifyRes.ok) throw new Error(`Google Sheets verification read failed (${verifyRes.status})`);\n      const verifyVals = (await verifyRes.json()).values || [];\n      const seen = new Set(verifyVals.map(r => String(r?.[0] || '').match(/(\\d{6}-\\d{3})/)?.[1]).filter(Boolean));\n      const missing = expectedBaseIds.filter(id => !seen.has(id));\n      if (missing.length) throw new Error(`Google Sheets verification missing Lab ID(s): ${missing.join(', ')}`);\n\n      context.log(`[Sheets] Wrote and verified ${rows.length} row(s) to Google Sheet ${data?.updates?.updatedRange || ''} in ${Date.now()-attemptStart}ms`);\n      return { success:true, updatedRange:data?.updates?.updatedRange || '', rows:rows.length, attempt };\n    } catch (e) {\n      lastError = e;\n      context.log(`[Sheets] attempt ${attempt}/3 failed after ${Date.now()-attemptStart}ms: ${e.message}`);\n      if (attempt < 3) await new Promise(resolve => setTimeout(resolve, attempt * 1500));\n    }\n  }\n  throw lastError || new Error('Google Sheets write failed after 3 attempts');\n}\n'''

if old_func not in s:
    raise SystemExit('writeToGoogleSheet target not found')
s = s.replace(old_func, new_func, 1)

old_call = '''        if (sheetRows.length) {\n          // Await the write before returning from the Azure Function. Fire-and-forget work\n          // can be terminated as soon as the request completes, which caused intermittent/missed COA rows.\n          const sheetResult = await Promise.race([\n            writeToGoogleSheet(sheetRows, context),\n            new Promise((_, rej) => setTimeout(() => rej(new Error('Google Sheets write timed out after 12 seconds')), 12000)),\n          ]);\n          coaSheetStatus = `written:${sheetResult.rows}`;\n        }\n'''
new_call = '''        if (sheetRows.length) {\n          // Fully await the Google write. The helper handles retries and verifies that\n          // the expected Lab IDs are present in column H before approval returns.\n          const sheetResult = await writeToGoogleSheet(sheetRows, context);\n          coaSheetStatus = `written:${sheetResult.rows}:attempt${sheetResult.attempt}`;\n        }\n'''
if old_call not in s:
    raise SystemExit('COA write call target not found')
s = s.replace(old_call, new_call, 1)

p.write_text(s)
